######################################################################
# Automatically generated by qmake (3.1) Fri Mar 21 10:59:18 2025
######################################################################

TEMPLATE = app
TARGET = ProgettoPAO
INCLUDEPATH += .
MOC_DIR = build/moc
OBJECTS_DIR = build/obj
QT += widgets gui core

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/grafica/bottoneSfoglia.h \
           src/grafica/mainWindow.h \
           src/grafica/mediaWidget.h \
           src/grafica/showMediaVisitor.h \
           src/jsonHandler/jsonVisitor.h \
           src/listaMedia/listaMedia.h \
           src/logica/album.h \
           src/logica/canzone.h \
           src/logica/libro.h \
           src/logica/media.h \
           src/logica/visitor.h
SOURCES += src/main.cpp \
           src/grafica/bottoneSfoglia.cpp \
           src/grafica/mainWindow.cpp \
           src/grafica/mediaWidget.cpp \
           src/grafica/showMediaVisitor.cpp \
           src/jsonHandler/jsonVisitor.cpp \
           src/listaMedia/listaMedia.cpp \
           src/logica/album.cpp \
           src/logica/cazone.cpp \
           src/logica/libro.cpp \
           src/logica/media.cpp
