######################################################################
# Automatically generated by qmake (3.1) Wed May 7 19:00:34 2025
######################################################################

TEMPLATE = app
TARGET = ProgettoPAO
INCLUDEPATH += .
MOC_DIR = build/moc
OBJECTS_DIR = build/obj
QT += widgets gui core

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/grafica/editorAlbum.h \
           src/grafica/editorCanzone.h \
           src/grafica/editorLibro.h \
           src/grafica/mainWindow.h \
           src/grafica/sceltaDettaglioVisitor.h \
           src/grafica/widgetAnteprima.h \
           src/grafica/widgetDettaglio.h \
           src/grafica/widgetEditorMedia.h \
           src/jsonHandler/jsonHandler.h \
           src/jsonHandler/jsonVisitor.h \
           src/logica/album.h \
           src/logica/canzone.h \
           src/logica/libro.h \
           src/logica/media.h \
           src/logica/visitor.h \
           src/mediaManager/filtraVisitor.h \
           src/mediaManager/mediaManager.h \
           src/mediaManager/searchVisitor.h
SOURCES += src/main.cpp \
           src/grafica/editorAlbum.cpp \
           src/grafica/editorCanzone.cpp \
           src/grafica/editorLibro.cpp \
           src/grafica/mainWindow.cpp \
           src/grafica/sceltaDettaglioVisitor.cpp \
           src/grafica/widgetAnteprima.cpp \
           src/grafica/widgetDettaglio.cpp \
           src/grafica/widgetEditorMedia.cpp \
           src/jsonHandler/jsonHandler.cpp \
           src/jsonHandler/jsonVisitor.cpp \
           src/logica/album.cpp \
           src/logica/cazone.cpp \
           src/logica/libro.cpp \
           src/logica/media.cpp \
           src/mediaManager/filtraVisitor.cpp \
           src/mediaManager/mediaManager.cpp \
           src/mediaManager/searchVisitor.cpp
